name: Build and upload zip to Github

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create environment file
        run: cp src/environments/environment.example.ts src/environments/environment.ts

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build:release


      - name: Get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Zip dist folder
        run: (cd dist/fastpoke-frontend/browser/ && zip -r ../../../fastpoke-kiosk.zip *)


      - name: Upload zipped app as release
        uses: softprops/action-gh-release@v2
        with:
          name: fastpoke-kiosk-${{steps.package-version.outputs.current-version}}
          files: fastpoke-kiosk.zip
          tag_name: ${{steps.package-version.outputs.current-version}}
          token: ${{ secrets.GITHUB_TOKEN }}
