name: Build and upload zip to Github

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: node-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build:release

      - name: Zip dist folder
        run: zip -r fastpoke-kiosk.zip dist/browser

      - name: Get app version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Upload zipped app as artifact
        uses: actions/upload-artifact@v2
        with:
          name: fastpoke-kiosk-${{steps.package-version.outputs.current-version}}
          path: fastpoke-kiosk-${{steps.package-version.outputs.current-version}}.zip
